#!/usr/bin/env python
from __future__ import with_statement
__all__ = ['Cloner', 'Workdir', 'Installer']

import os
import sys
import urllib
import shutil
import tempfile
import zipfile
import mercurial
from functools import partial

# Ensure correct dist folder
try:
    os.mkdir('dist')
except OSError:
    pass
try:
    os.unlink(os.path.join('dist', 'dev'))
except OSError:
    pass
os.symlink(os.path.join('..', 'dev'), os.path.join('dist', 'dev'))

try:
    import _genexecutables
except ImportError:
    from . import _genexecutables

hivename = 'zicbee.zip'
ADM_PREFIX = 'sudo ' if os.system('sudo -v') == 0 else '' # XXX: os independent way ?
STATIC_EXTENSIONS = [] # for now sounds fine with pkg_resources :)
DEV_DIR = 'dev'
DIST_DIR = 'dist'

try:
    zipfile.ZipFile.extractall
except AttributeError:
    # python2.5 compatibility
    def _my_extractall(self, to_path, members):
        if not members:
            members = self.infolist()

        dirs = []
        for memb in members:
            root = to_path
            for d in memb.filename.split('/')[:-1]:
                root += os.path.sep + d
                if root not in dirs:
                    dirs.append(root)
                    if not os.path.exists(root):
                        os.mkdir(root)

            fullpath = os.path.join(to_path, memb.filename)
            file(fullpath, "w").write(self.read(memb.filename))

    zipfile.ZipFile.extractall = _my_extractall


class Zipper(list):
    """ Object used to handle zip files """
    def __init__(self, zipname):
        self.name = zipname

    def extract(self, name=None, to_path=None, members=None, load=False):
        name = name or self.name
        zf = zipfile.ZipFile(name)
        if load:
            self[:] = [(x, '') for x in zf.namelist()]
        zf.extractall(to_path, members)
        zf.close()

    def save(self, as_name=None, prefix=''):
        name = as_name or self.name
        zf = zipfile.ZipFile(name, 'w', zipfile.ZIP_DEFLATED)
        for fname, dirname in self:
            zf.write(fname, prefix+fname[len(dirname):])
        zf.close()

class Cloner(object):
    """ After instantiation, you can use the get(name) method to get a zicbee component
    If mercurial is installed, it will use it, if not, just get the latest version zipfile and unpack
    """

    HOST = "http://zicbee.gnux.info/hg"
    BRANCH = "default" # change to "default" to get the stable version or tip to get latest

    def _hg_get(self, name):
        uri = "%s/%s"%(self.HOST, name)
        try:
            self._hg_clone(uri)
        except Exception, e:
            repo = self._hg_repo(name, False)
            self._hg_pull(repo, uri)
            self._hg_up(repo, self.BRANCH)

    def _failsafe_get(self, name):
        uri = "%s/%s/archive/%s.zip"%(self.HOST, name, self.BRANCH)
        zipname = "%s.zip"%name
        site = urllib.urlretrieve(uri, zipname)
        zp = Zipper(zipname)
        zp.extract(load=True)
        dirname = zp[0][0].split( '/', 1)[0]
        if os.path.exists( os.path.join( name, '.hg')):
            print 'You are about to destroy the %s repository.\nIf you don\'t, zip file content is kept under "%s".'%(name, os.path.join(os.getcwd(), dirname))
            yn = raw_input('Do you want to proceed [yN] ? ')
            if not yn or yn[0].lower() != 'y':
                print "Not overwriting, install mercurial to have good update support."
                return
        shutil.rmtree(name)
        os.rename( dirname, name)

    def __init__(self):
        try:
            import mercurial.ui
            import mercurial.commands
            import mercurial.localrepo
            ui = mercurial.ui.ui()
            self._hg_clone = partial(mercurial.commands.clone, ui)
            self._hg_pull = partial(mercurial.commands.pull, ui)
            self._hg_up = partial(mercurial.commands.update, ui)
            self._hg_repo = partial(mercurial.localrepo.instance, ui)

        except ImportError:
            print "Can't use Mercurial :'("
            self.get = self._failsafe_get
        else:
            self.get = self._hg_get

class Workdir(object):
    """ Class to use with 'with' keyword, argument is a directory name.
    It will ensure the directory is properly created and chdir into it.
    """
    def __init__(self, name):
        self.old_path = os.getcwd()
        self.dirname = name

    def __enter__(self):
        for action in os.mkdir, os.chdir:
            try:
                action(self.dirname)
            except OSError, e:
                if e.args[0] != 17:
                    print "Can't %s : %s"%(action.__name__, e)
        return self.old_path

    def __exit__(self, a, b, c):
        os.chdir(self.old_path)

def rm(n):
    if os.path.exists(n):
        if os.path.isdir(n):
            shutil.rmtree(n)
        else:
            os.unlink(n)

class TempDir(object):
    def __init__(self):
        self.name = tempfile.mkdtemp('bee_', '_hive')

    def __enter__(self):
        return self.name

    def __exit__(self, a, b, c):
        print "Clean up..."
        rm(self.name)

class Installer(object):
    """ Zicbee installer object, all the high-level commands are here.
    The list of dependencies are hold in self.deps and the zicbee related projects are in self.softs
    Generally speaking, if things are not in place, then create it
    The methods can be directly linked to script arguments
    All commands assume you are in the parent directory of the copy of the project.
    """

    softs = 'zicbee-lib zicbee zicbee-mplayer zicbee-vlc zicbee-gst'.split()
    deps = "simplejson web.py buzhug mutagen".split()

    packages_extras = {
            'web.py' : '-f http://webpy.org/static/',
            'buzhug' : '-f http://sourceforge.net/projects/buzhug/files/',
            'mutagen' : '-f http://code.google.com/p/mutagen/downloads/list',
        }

    def __init__(self):
        self.cloner = Cloner()
        self._egg_created = False
        self.force_gen = partial(self._gen_package, forced=True)
        self.std_gen = partial(self._gen_package, forced=False)

    def _mk_egg_info(self):
        EMPTY, INI, MERGE, CAT, SCAT = xrange(5)
        egg_files = {
            'dependency_links.txt': MERGE,
            'entry_points.txt': INI,
            'not-zip-safe': ' ',
            'PKG-INFO': 'pkg:zicbee',
            'requires.txt': EMPTY,
            'SOURCES.txt': SCAT,
            'top_level.txt': SCAT,
            'spec/depend': """metadata_version = '1.1'
name = 'zicbee'
version = '0.9'
build = 1

arch = None
platform = 'linux2'
osdist = None
python = '2.5'
packages = [
  'buzhug 1.5',
  'mutagen 1.18',
  'web.py 0.32',
  'zicbee-lib 0.6',
  'zicbee-mplayer 0.9',
  'zicbee-vlc 0.9',
  'zicbee-gst 0.6',
]
            """,
          }
        def safe_readlines(path, mode='r'):
            try:
                return [l.strip() for l in file(path, mode).readlines()]
            except IOError:
                print "no %s"%path
                return []

        def info_name(s):
            return s.replace('-', '_')+'.egg-info'

        print os.getcwd()
        for prop, data in egg_files.iteritems():
            deps = dict((dep, safe_readlines(os.path.join(DEV_DIR, dep, info_name(dep), prop)))
             for dep in self.softs)
            for addon in self.deps:
                deps[addon] = safe_readlines(os.path.join(DIST_DIR, addon, info_name(addon), prop))
            if data == MERGE:
                d = set()
                for dep, content in deps.iteritems():
                    d.update(content)
                content = '\n'.join(sorted(d))
                del d
            elif data in (CAT, SCAT):
                lines = []
                for dep, content in deps.iteritems():
                    lines.extend(content)
                if data == SCAT:
                    lines = sorted(lines)
                content = '\n'.join(lines)
                del lines
            elif data == INI:
                ini_file = {None:set()}
                for dep, content in deps.iteritems():
                    cur_section = None
                    for line in content:
                        if not line or line.startswith('eggsecutable'):
                            continue
                        if line[0] == '[':
                            cur_section = line[1:-1].strip()
                            if cur_section not in ini_file:
                                ini_file[cur_section] = set()
                            continue
                        ini_file[cur_section].add(line)
                result = []
                for section in sorted(ini_file.iterkeys()):
                    if section is not None:
                        result.append('[%s]'%section)
                    else:
                        if not ini_file[section]:
                            continue
                    for line in sorted(ini_file[section]):
                        result.append(line)
                    result.append('')
                content = '\n'.join(result)
                del result
                del ini_file
            elif data == EMPTY:
                content = ''
            elif data.startswith('pkg:'):
                for dep, content in deps.iteritems():
                    if dep == data[4:]:
                        content = '\n'.join(content)
                        break
            else:
                content = data

            file(os.path.join(DEV_DIR, 'EGG-INFO', prop), 'w').write(content)


    def _gen_package(self, *args, **kw):
        """ Will generate %s """%hivename
        forced = kw.pop('forced', False)

        # TODO: create "build" command that is called here
        j = os.path.join
        with TempDir() as tempdir:
            packages = self.deps + [j(DEV_DIR, p) for p in self.softs]
            egg_name = 'bee.egg'

            zipper = Zipper(j(os.getcwd(), egg_name))
            for pkg in packages:
                fullpath = j(DIST_DIR, pkg)
                egg = fullpath + '.egg'
                # if forced remove everything
                # BUT if you give arguments, only the specified ones are removed
                if (forced and (not args or pkg.rsplit(os.sep, 1)[-1] in args)) or not os.path.exists(egg):
                    if not os.path.isfile(egg):
                        if not os.path.isdir(fullpath):
                            os.system("easy_install -U -e %s -b '%s' '%s'"%(self.packages_extras.get(pkg, ''), DIST_DIR, pkg))
                        for e in os.listdir(fullpath):
                            if e.endswith('.egg'):
                                rm(j(fullpath, DIST_DIR, e))
                    with Workdir(fullpath):
                        rm(j(fullpath, 'build'))
                        rm(j(fullpath, DIST_DIR))
                        os.system('''python -c "import setuptools; execfile('setup.py')" bdist_egg''')
                        egg_file = [j(fullpath, DIST_DIR, e) for e in os.listdir(DIST_DIR) if e.endswith('.egg')][0]
                    shutil.move(egg_file, egg)
                print "extracting %s..."%egg
                zipper.extract(egg, tempdir)

            for unwanted in 'share', 'EGG-INFO':
                rm(j(tempdir, unwanted))

            for root, dirs, files in os.walk(tempdir):
                for d in dirs:
                    if d.startswith('test'):
                        rm(j(root, d))
            self._mk_egg_info()
            shutil.copytree(j(DEV_DIR, 'EGG-INFO'), j(tempdir, 'EGG-INFO'))
            static_files = []
            for r, d, f in os.walk(tempdir):
                for n in f:
                    if n == '_speedups.py':
                        continue
                    ext = n.rsplit('.', 1)[-1]
                    if ext in STATIC_EXTENSIONS:
                        static_files.append((j(r,n), tempdir))
                    elif ext not in ('pyo', 'pyc', 'swp', 'rej', 'so'):
                        zipper.append((j(r, n), tempdir))

            print "Saving %s..."%zipper.name
            zipper.save()
            with Workdir(tempdir) as old_dir:
                for fname in zipper:
                    rm(fname[0])
            rm(hivename)
            executables = [(e[0], '') for e in _genexecutables.executables]
            zipper[:] = static_files
            zipper.append((egg_name, ''))
            zipper.extend(executables)
            print "Saving %s..."%hivename
            sys.path.insert(0, os.path.join(os.curdir, egg_name))
            from zicbee import __version__ as ver
            sys.path.pop(0)
            root, ext = hivename.rsplit('.', 1)
            zipname = j("%s-%s.%s"%(root, ver, ext))

            foldername = zipname[:-4]
            zipper.save(zipname, prefix='%s%s'%(foldername, os.sep))
            print "Testing by extracting..."
            zipper.extract(zipname, members=(foldername + x[0][len(x[1]):] for x in static_files))
            with Workdir('release'):
                shutil.move(j(os.pardir, zipname), j(os.curdir, zipname))

    def cleanup(self, name):
        """ Will clean up .pyo and .pyc files in the given directory """
        for root, dirs, files in os.walk(name):
            for fname in files:
                if fname[-4:] in ('.pyo', '.pyc'):
                    os.unlink(os.path.join(root, fname))

    def pull(self, name):
        """ Clones the given project name """
        self.cloner.get(name)

    def mkbin(self):
        _genexecutables.gen()

    def install(self, name):
        """ Installs project via easy_install .pth files (links to project)  """
        cmd = '%s%s develop'%(ADM_PREFIX, os.path.join(os.curdir, 'setup.py'))

        with Workdir(name):
            os.chmod('setup.py', 0755)
            if os.system(cmd) != 0:
                raise RuntimeError("Can't run %s!"%cmd)

def change_branch(branch=None):
    t = {'stable': 'default',
            'dev': 'tip'}
    rt = {'default': 'stable',
            'tip': 'dev'}

    if not branch:
        print "Set to:", rt.get(Cloner.BRANCH, Cloner.BRANCH)
        print "available choices: %s"%(', '.join(t.keys()))
    else:
        f = file(sys.argv[0], 'r+')
        data = f.readlines()
        suspect_line = [(i, l) for i, l in enumerate(data) if l.startswith('    BRANCH = ')]
        if len(suspect_line) != 1:
            raise RuntimeError('Incorrect "%s" program!'%sys.argv[0])
        else:
            suspect_line = suspect_line[0]

        f.seek(0)
        f.truncate()
        name = t.get(branch, branch)
        data[suspect_line[0]] = '    BRANCH = "%s"\n'%name
        Cloner.BRANCH = name
        f.writelines(data)

if __name__ == '__main__':
    inst_tool = Installer()
    default_cmds = ('pull', 'cleanup', 'mkbin', 'gen')
    commands = sys.argv[1:] if len(sys.argv)>1 else default_cmds
    l = []
    def print_help():
        print """Usage: %s <command> [command]...

If no parameter is given, will execute: %s.
This is the ideal for the first run,
replace "gen" with "fgen" or remove all .egg files for a full update.

Commands:
gen     : Generates the %s, re-build project from sources if of the sources eggs are missing
fgen    : Generates the %s, re-build project from sources unconditionally
          you can limit the rebuilding to specified packages. Ex: fgen.zicbee-lib.zicbee
pull    : Pull latest changes from server, clone if not already here,
          fallbacks to unversioned folder (from zip).
mkbin   : Recreates the executable
cleanup : Removes those .pyc & .pyo files from projects
branch  : Sets the release mode (use branch.dev to switch to beta test mode ...)
          WARN: changes will be saved into executable
install : Easy_install develop zicbee related projects

Submit bugs with http://code.google.com/p/zicdb/issues/entry :)"""%(sys.argv[0], ', '.join(default_cmds), hivename, hivename)

    cmd_handlers = {
            'gen': inst_tool.std_gen,
            'fgen': inst_tool.force_gen,
            'mkbin': inst_tool.mkbin,
            'branch': change_branch,
            'help': print_help
            }

    global_cmds = []
    per_proj_cmds = []
    for cmd in commands:
        cmdlist = cmd.split('.')
        if cmdlist:
            cmd = cmdlist[0]
            args = cmdlist[1:]
        else:
            args = []
        if cmd in cmd_handlers:
            global_cmds.append((cmd, args))
        else:
            per_proj_cmds.append((cmd, args))

    if per_proj_cmds:
        with Workdir(DEV_DIR):
            commands = [(getattr(inst_tool, cmd), args) for cmd, args in per_proj_cmds if hasattr(inst_tool, cmd)]
            for soft in inst_tool.softs:
                for fn, args in commands:
                    name = "%s.%s"%(soft, fn.func_name)
                    try:
                        fn(soft, *args)
                    except Exception, e:
                        l.append( (name, e) )
                    else:
                        l.append( (name, True) )

        if l:
            print "Status:"
            for name, res in l:
                print "[%s] %s"%(name, "OK" if res is True else res)
        else:
            print 'try "%s help".'%sys.argv[0]

    for cmd, args in global_cmds:
        cmd_handlers[cmd](*args)

